import{applyHomography,clamp01,computeHomography,detectColorBlob}from'./src/tracker-core.js';

const $=s=>document.querySelector(s);
const ui={start:$('#startCamera'),stop:$('#stopCamera'),select:$('#cameraSelect'),video:$('#cameraVideo'),camera:$('#cameraCanvas'),game:$('#gameCanvas'),cameraStatus:$('#cameraStatus'),trackingStatus:$('#trackingStatus'),fps:$('#fpsValue'),mirror:$('#mirrorCamera'),debug:$('#debugOverlay'),hueMin:$('#hueMin'),hueMax:$('#hueMax'),satMin:$('#satMin'),valMin:$('#valMin'),minArea:$('#minArea'),smoothing:$('#smoothing'),lost:$('#lostBehavior'),calStart:$('#calibrationStart'),calCapture:$('#calibrationCapture'),calReset:$('#calibrationReset'),calText:$('#calibrationText'),calProgress:$('#calibrationProgress'),rawX:$('#rawX'),rawY:$('#rawY'),smoothX:$('#smoothX'),smoothY:$('#smoothY'),velocityX:$('#velocityX'),velocityY:$('#velocityY'),speed:$('#speedValue'),confidence:$('#confidenceValue')};
const values={hueMin:$('#hueMinValue'),hueMax:$('#hueMaxValue'),satMin:$('#satMinValue'),valMin:$('#valMinValue'),minArea:$('#minAreaValue'),smoothing:$('#smoothingValue')};
const cctx=ui.camera.getContext('2d',{willReadFrequently:true}),gctx=ui.game.getContext('2d'),work=document.createElement('canvas'),wctx=work.getContext('2d',{willReadFrequently:true});
const S={stream:null,running:false,raf:0,frames:0,fpsAt:performance.now(),last:performance.now(),smooth:{x:.5,y:.5},prev:{x:.5,y:.5},det:null,cal:{active:false,step:0,points:[],h:null}};
const labels=['top-left','top-right','bottom-right','bottom-left'],dst=[{x:0,y:0},{x:1,y:0},{x:1,y:1},{x:0,y:1}];

function sync(){values.hueMin.textContent=ui.hueMin.value+'°';values.hueMax.textContent=ui.hueMax.value+'°';values.satMin.textContent=ui.satMin.value+'%';values.valMin.textContent=ui.valMin.value+'%';values.minArea.textContent=Number(ui.minArea.value).toFixed(2)+'%';values.smoothing.textContent=Number(ui.smoothing.value).toFixed(2)}
function options(){return{hueMin:+ui.hueMin.value,hueMax:+ui.hueMax.value,saturationMin:+ui.satMin.value,valueMin:+ui.valMin.value,minAreaRatio:+ui.minArea.value/100,sampleStep:2}}
function fmt(n,d=3){return Number.isFinite(n)?n.toFixed(d):'—'}
async function cameras(){const ds=await navigator.mediaDevices.enumerateDevices(),cs=ds.filter(d=>d.kind==='videoinput'),cur=ui.select.value;ui.select.replaceChildren();cs.forEach((c,i)=>{const o=document.createElement('option');o.value=c.deviceId;o.textContent=c.label||'Camera '+(i+1);ui.select.append(o)});if(cs.some(c=>c.deviceId===cur))ui.select.value=cur;ui.select.disabled=cs.length<2}
function stop(){S.running=false;cancelAnimationFrame(S.raf);S.stream?.getTracks().forEach(t=>t.stop());S.stream=null;ui.video.srcObject=null;ui.start.disabled=false;ui.stop.disabled=true;ui.select.disabled=true;ui.cameraStatus.textContent='Camera stopped';ui.trackingStatus.textContent='No signal';drawGame(true)}
async function start(device=''){stop();if(!navigator.mediaDevices?.getUserMedia){ui.cameraStatus.textContent='Camera API unavailable';return}try{ui.cameraStatus.textContent='Requesting camera…';const video={width:{ideal:1280},height:{ideal:720},frameRate:{ideal:30,max:60}};if(device)video.deviceId={exact:device};else video.facingMode={ideal:'user'};S.stream=await navigator.mediaDevices.getUserMedia({video,audio:false});ui.video.srcObject=S.stream;await ui.video.play();await cameras();S.running=true;S.last=performance.now();S.frames=0;S.fpsAt=S.last;ui.start.disabled=true;ui.stop.disabled=false;ui.cameraStatus.textContent='Camera live';S.raf=requestAnimationFrame(loop)}catch(e){console.error(e);ui.cameraStatus.textContent=window.isSecureContext?'Could not start camera':'Use localhost or HTTPS'}}
function prep(){const sw=ui.video.videoWidth||1280,sh=ui.video.videoHeight||720,a=sw/sh;work.width=320;work.height=Math.max(180,Math.round(320/a));ui.camera.width=960;ui.camera.height=Math.round(960/a)}
function mapped(d){const p=applyHomography({x:ui.mirror.checked?1-d.x:d.x,y:d.y},S.cal.h);return{x:clamp01(p.x),y:clamp01(p.y)}}
function drawCamera(d){const w=ui.camera.width,h=ui.camera.height;cctx.save();if(ui.mirror.checked){cctx.translate(w,0);cctx.scale(-1,1)}cctx.drawImage(ui.video,0,0,w,h);cctx.restore();if(!ui.debug.checked||!d)return;const b=d.bbox,x=(ui.mirror.checked?1-b.x-b.width:b.x)*w,y=b.y*h,cx=(ui.mirror.checked?1-d.x:d.x)*w,cy=d.y*h;cctx.strokeStyle=cctx.fillStyle='#56e36f';cctx.lineWidth=4;cctx.strokeRect(x,y,b.width*w,b.height*h);cctx.beginPath();cctx.arc(cx,cy,8,0,Math.PI*2);cctx.fill()}
function sizeGame(){const r=ui.game.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,2),w=Math.max(1,Math.round(r.width*d)),h=Math.max(1,Math.round(r.height*d));if(ui.game.width!==w||ui.game.height!==h){ui.game.width=w;ui.game.height=h}return{w,h}}
function drawGame(force=false){const{w,h}=sizeGame();gctx.clearRect(0,0,w,h);gctx.strokeStyle='rgba(255,255,255,.08)';for(let i=1;i<4;i++){gctx.beginPath();gctx.moveTo(w*i/4,0);gctx.lineTo(w*i/4,h);gctx.stroke();gctx.beginPath();gctx.moveTo(0,h*i/4);gctx.lineTo(w,h*i/4);gctx.stroke()}let visible=!force&&S.det,x=S.smooth.x,y=S.smooth.y,a=visible?1:0;if(!visible&&ui.lost.value==='hold')a=.35;if(!visible&&ui.lost.value==='center'){x+=(.5-x)*.04;y+=(.5-y)*.04;S.smooth={x,y};a=.25}if(!a)return;const px=x*w,py=y*h,r=Math.max(16,Math.min(w,h)*.035);gctx.globalAlpha=a;gctx.strokeStyle='#56e36f';gctx.fillStyle='rgba(86,227,111,.18)';gctx.lineWidth=Math.max(3,r*.12);gctx.beginPath();gctx.arc(px,py,r,0,Math.PI*2);gctx.fill();gctx.stroke();gctx.beginPath();gctx.moveTo(px-r*1.45,py);gctx.lineTo(px+r*1.45,py);gctx.moveTo(px,py-r*1.45);gctx.lineTo(px,py+r*1.45);gctx.stroke();gctx.globalAlpha=1}
function telemetry(raw,now,d){const dt=Math.max(.001,(now-S.last)/1000),vx=(S.smooth.x-S.prev.x)/dt,vy=(S.smooth.y-S.prev.y)/dt;ui.rawX.textContent=raw?fmt(raw.x):'—';ui.rawY.textContent=raw?fmt(raw.y):'—';ui.smoothX.textContent=d?fmt(S.smooth.x):'—';ui.smoothY.textContent=d?fmt(S.smooth.y):'—';ui.velocityX.textContent=d?fmt(vx,2):'—';ui.velocityY.textContent=d?fmt(vy,2):'—';ui.speed.textContent=d?fmt(Math.hypot(vx,vy),2):'—';ui.confidence.textContent=d?Math.round(d.confidence*100)+'%':'—';ui.trackingStatus.textContent=d?'Object tracked':'Searching for green…'}
function loop(now){if(!S.running)return;if(ui.video.readyState<2){S.raf=requestAnimationFrame(loop);return}prep();wctx.drawImage(ui.video,0,0,work.width,work.height);const d=detectColorBlob(wctx.getImageData(0,0,work.width,work.height),options());S.det=d;let raw=null;S.prev={...S.smooth};if(d){raw=mapped(d);const a=+ui.smoothing.value;S.smooth.x+=(raw.x-S.smooth.x)*a;S.smooth.y+=(raw.y-S.smooth.y)*a}drawCamera(d);drawGame();telemetry(raw,now,d);S.frames++;if(now-S.fpsAt>=500){ui.fps.textContent=(S.frames*1000/(now-S.fpsAt)).toFixed(1);S.frames=0;S.fpsAt=now}S.last=now;S.raf=requestAnimationFrame(loop)}
function calStart(){S.cal={active:true,step:0,points:[],h:null};ui.calText.textContent='Hold the green object at the '+labels[0]+' of your play area, then capture.';ui.calProgress.textContent='0 / 4 points'}
function capture(){if(!S.cal.active||!S.det)return;S.cal.points.push({x:ui.mirror.checked?1-S.det.x:S.det.x,y:S.det.y});S.cal.step++;ui.calProgress.textContent=S.cal.step+' / 4 points';if(S.cal.step===4){S.cal.h=computeHomography(S.cal.points,dst);S.cal.active=false;ui.calCapture.disabled=true;ui.calText.textContent=S.cal.h?'Calibration active. Your captured corners map to the full game surface.':'Calibration failed. Reset and try again.'}else ui.calText.textContent='Captured. Now hold the object at the '+labels[S.cal.step]+' and capture.'}
function reset(){S.cal={active:false,step:0,points:[],h:null};ui.calCapture.disabled=true;ui.calText.textContent='Optional: map any four physical corners to the full game surface.';ui.calProgress.textContent='Not calibrated'}

ui.start.addEventListener('click',()=>start(ui.select.value));ui.stop.addEventListener('click',stop);ui.select.addEventListener('change',()=>S.running&&start(ui.select.value));ui.calStart.addEventListener('click',calStart);ui.calCapture.addEventListener('click',capture);ui.calReset.addEventListener('click',reset);window.addEventListener('resize',()=>drawGame());
[ui.hueMin,ui.hueMax,ui.satMin,ui.valMin,ui.minArea,ui.smoothing].forEach(x=>x.addEventListener('input',sync));setInterval(()=>{if(S.cal.active)ui.calCapture.disabled=!S.det},100);sync();drawGame(true);
