import test from 'node:test';
import assert from 'node:assert/strict';
import {evaluateFederationOperation,upsertFederationOperationRequest,appendFederationOperationEvent,federationOperationAgentContext,federationGovernedOperationsCapability} from '../src/federation-governed-operations-core.js';
const HOME='11111111-1111-4111-8111-111111111111';
const OFFICE='22222222-2222-4222-8222-222222222222';
const base=()=>({local_site_id:HOME,actor:{actor_id:'u1',actor_type:'owner'},federation_health:{local_site_id:HOME,sites:[{site_id:HOME,state:'current',fresh:true,recovery_complete:true},{site_id:OFFICE,state:'current',fresh:true,recovery_complete:true}]},access:{peers:[{site_id:OFFICE,policy_peer_allowed:true}]},fleet_health:{local_site_id:HOME,sites:[{site_id:HOME,state:'healthy',devices:[{device_id:'hs-home'}]},{site_id:OFFICE,state:'healthy',devices:[{device_id:'hs-office'}]}]}});
test('reconcile request is eligible but completion requires authoritative reconciliation',()=>{const i=base();const r=evaluateFederationOperation({...i,operation_type:'reconcile',target_site_id:OFFICE,request_id:'req-reconcile'},1000);assert.equal(r.state,'approved');assert.equal(r.requires_reconciliation,true);let l=upsertFederationOperationRequest([],r);l=appendFederationOperationEvent(l,{request_id:r.request_id,state:'queued'},1100);l=appendFederationOperationEvent(l,{request_id:r.request_id,state:'running'},1200);l=appendFederationOperationEvent(l,{request_id:r.request_id,state:'reconciling'},1300);assert.throws(()=>appendFederationOperationEvent(l,{request_id:r.request_id,state:'completed',reconciliation:{state:'current',fresh:false,recovery_complete:true}},1400),/authoritative_reconciliation_required/);l=appendFederationOperationEvent(l,{request_id:r.request_id,state:'completed',reconciliation:{state:'current',fresh:true,recovery_complete:true}},1500);assert.equal(l[0].state,'completed');});
test('agent may propose but cannot execute',()=>{const i=base();i.actor={actor_id:'agent',actor_type:'agent'};const r=evaluateFederationOperation({...i,operation_type:'reconnect',target_site_id:OFFICE,request_id:'req-agent'},1000);assert.equal(r.state,'awaiting_approval');assert.equal(r.executable,false);assert.ok(r.reason_codes.includes('agent_may_propose_only'));});
test('revocation blocks remote operation',()=>{const i=base();i.access.peers[0].policy_peer_allowed=false;i.access.peers[0].revoked=true;const r=evaluateFederationOperation({...i,operation_type:'reconcile',target_site_id:OFFICE,request_id:'req-revoked'},1000);assert.equal(r.state,'rejected');assert.ok(r.reason_codes.includes('federation_access_revoked'));});
test('authority transfer requires explicit confirmation, local source, current state, epoch advance, and reconciliation',()=>{const i=base();let r=evaluateFederationOperation({...i,operation_type:'transfer_authority',target_site_id:HOME,new_authority_device_id:'hs-new',request_id:'req-transfer'},1000);assert.equal(r.state,'rejected');assert.ok(r.reason_codes.includes('explicit_confirmation_required'));r=evaluateFederationOperation({...i,operation_type:'transfer_authority',target_site_id:HOME,new_authority_device_id:'hs-new',confirmation_token:'confirm',request_id:'req-transfer-ok'},1000);assert.equal(r.state,'awaiting_approval');r.authority_epoch_before=7;let l=upsertFederationOperationRequest([],r);l=appendFederationOperationEvent(l,{request_id:r.request_id,state:'approved'},1100);l=appendFederationOperationEvent(l,{request_id:r.request_id,state:'queued'},1200);l=appendFederationOperationEvent(l,{request_id:r.request_id,state:'running'},1300);l=appendFederationOperationEvent(l,{request_id:r.request_id,state:'reconciling'},1400);assert.throws(()=>appendFederationOperationEvent(l,{request_id:r.request_id,state:'completed',authority_epoch_after:7,reconciliation:{state:'current',fresh:true,recovery_complete:true}},1500),/authority_epoch_must_advance/);l=appendFederationOperationEvent(l,{request_id:r.request_id,state:'completed',authority_epoch_after:8,reconciliation:{state:'current',fresh:true,recovery_complete:true}},1500);assert.equal(l[0].authority_epoch_after,8);});
test('idempotency key deduplicates identical requests and rejects semantic conflict',()=>{const i=base();const a=evaluateFederationOperation({...i,operation_type:'reconnect',target_site_id:OFFICE,request_id:'a',idempotency_key:'same'},1000);const b=evaluateFederationOperation({...i,operation_type:'reconnect',target_site_id:OFFICE,request_id:'b',idempotency_key:'same'},1001);let l=upsertFederationOperationRequest([],a);l=upsertFederationOperationRequest(l,b);assert.equal(l.length,1);const c=evaluateFederationOperation({...i,operation_type:'reconcile',target_site_id:OFFICE,request_id:'c',idempotency_key:'same'},1002);assert.throws(()=>upsertFederationOperationRequest(l,c),/idempotency_conflict/);});
test('terminal state is immutable',()=>{const i=base();const r=evaluateFederationOperation({...i,operation_type:'reconnect',target_site_id:OFFICE,request_id:'done'},1000);let l=upsertFederationOperationRequest([],r);l=appendFederationOperationEvent(l,{request_id:r.request_id,state:'queued'},1100);l=appendFederationOperationEvent(l,{request_id:r.request_id,state:'running'},1200);l=appendFederationOperationEvent(l,{request_id:r.request_id,state:'completed',reconciliation:{state:'current',fresh:true,recovery_complete:true}},1300);assert.throws(()=>appendFederationOperationEvent(l,{request_id:r.request_id,state:'failed'},1400),/terminal_operation/);});
test('agent context and capability preserve execution and recovery boundaries',()=>{const cap=federationGovernedOperationsCapability();assert.equal(cap.cloud_execution_allowed,false);assert.equal(cap.agent_proposal_only,true);assert.equal(cap.authority_transfer_automatic,false);assert.equal(cap.completion_requires_authoritative_reconciliation,true);const ctx=federationOperationAgentContext([]);assert.equal(ctx.agent_may_execute,false);assert.equal(ctx.cloud_may_execute,false);});

test('site revocation is high-risk and cannot revoke the local origin site',()=>{const i=base();let r=evaluateFederationOperation({...i,operation_type:'revoke_site',target_site_id:OFFICE,request_id:'revoke-site'},1000);assert.equal(r.state,'awaiting_approval');r=evaluateFederationOperation({...i,operation_type:'revoke_site',target_site_id:HOME,request_id:'revoke-local'},1000);assert.equal(r.state,'rejected');assert.ok(r.reason_codes.includes('revoke_site_must_target_peer'));});
